roster_writer.writerow([" ", f'{alldays[28].date}'])
roster_writer.writerow(["AM Main:", f'{alldays[28].AMDC.name}'])
roster_writer.writerow(["PM Main:", f'{alldays[28].PMDC.name}'])
roster_writer.writerow(" ")
roster_writer.writerow(["AM Reserve:", f'{alldays[28].AMreserve.name}'])
roster_writer.writerow(["PM Reserve:", f'{alldays[28].PMreserve.name}'])
roster_writer.writerow(" ")

roster_writer.writerow([" ", f'{alldays[28].date}', f'{alldays[29].date}'])
roster_writer.writerow(["AM Main:", f'{alldays[28].AMDC.name}', f'{alldays[29].AMDC.name}'])
roster_writer.writerow(["PM Main:", f'{alldays[28].PMDC.name}', f'{alldays[29].PMDC.name}'])
roster_writer.writerow(" ")
roster_writer.writerow(["AM Reserve:", f'{alldays[28].AMreserve.name}', f'{alldays[29].AMreserve.name}'])
roster_writer.writerow(["PM Reserve:", f'{alldays[28].PMreserve.name}', f'{alldays[29].PMreserve.name}'])
roster_writer.writerow(" ")

roster_writer.writerow([" ", f'{alldays[28].date}', f'{alldays[29].date}', f'{alldays[30].date}'])
roster_writer.writerow(["AM Main:", f'{alldays[28].AMDC.name}', f'{alldays[29].AMDC.name}', f'{alldays[30].AMDC.name}'])
roster_writer.writerow(["PM Main:", f'{alldays[28].PMDC.name}', f'{alldays[29].PMDC.name}', f'{alldays[30].PMDC.name}'])
roster_writer.writerow(" ")
roster_writer.writerow(["AM Reserve:", f'{alldays[28].AMreserve.name}', f'{alldays[29].AMreserve.name}', f'{alldays[30].AMreserve.name}'])
roster_writer.writerow(["PM Reserve:", f'{alldays[28].PMreserve.name}', f'{alldays[29].PMreserve.name}', f'{alldays[30].PMreserve.name}'])
roster_writer.writerow(" ")